name: aqi
channels:
  - defaults
dependencies:
  - aiodns=3.5.0=py312hca03da5_0
  - aiohappyeyeballs=2.6.1=py312hca03da5_0
  - aiohttp=3.12.15=py312h79febb2_0
  - aiosignal=1.4.0=py312hca03da5_0
  - attrs=24.3.0=py312hca03da5_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py312ha86b861_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.9.9=hca03da5_0
  - cffi=2.0.0=py312h3a083c1_0
  - expat=2.7.1=h313beb8_0
  - frozenlist=1.5.0=py312h80987f9_0
  - idna=3.7=py312hca03da5_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.30=hf2bb037_0
  - libuv=1.48.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - multidict=6.7.0=py312h254cc4a_0
  - ncurses=6.5=hee39554_0
  - numexpr=2.11.0=py312h8c72970_1
  - numpy=2.3.3=py312hc95ac1c_1
  - numpy-base=2.3.3=py312h8087a70_1
  - openssl=3.0.18=h9b4081a_0
  - pandas=2.3.3=py312hc6ded6b_0
  - pip=25.2=pyhc872135_1
  - propcache=0.3.1=py312h80987f9_0
  - pycares=4.10.0=py312h091efcb_0
  - pycparser=2.23=py312hca03da5_0
  - python=3.12.12=ha3d41b5_0
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312hca03da5_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py312hca03da5_0
  - six=1.17.0=py312hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - uvloop=0.21.0=py312h80987f9_0
  - wheel=0.45.1=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yarl=1.18.0=py312h80987f9_0
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.0
      - black==25.9.0
      - click==8.3.0
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - executing==2.2.1
      - ipykernel==7.0.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - matplotlib-inline==0.1.7
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - packaging==25.0
      - parso==0.8.5
      - pathspec==0.12.1
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pytokens==0.2.0
      - pyzmq==27.1.0
      - stack-data==0.6.3
      - tornado==6.5.2
      - traitlets==5.14.3
      - wcwidth==0.2.14
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/aqi
